# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 14:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(verbose_name=b'ZIP Code')),
                ('house_number', models.CharField(blank=True, max_length=40, verbose_name=b'House Number')),
                ('street_name', models.CharField(blank=True, max_length=40, verbose_name=b'Street Name')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name=b'City')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name=b'First Name')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name=b'Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name=b'E-mail Address')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile(b'^\\+?1?\\d{9,15}$'), b'Enter a valid phone number.', b'invalid')], verbose_name=b'Telephone')),
                ('date_of_birth', models.DateField(verbose_name=b'Date of Birth')),
                ('gender', models.IntegerField(choices=[(1, b'Female'), (2, b'Male')])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=40, verbose_name=b'Product Name')),
                ('product_type', models.IntegerField(choices=[(b'DATA', b'Data'), (b'VOICE', b'Voice'), (b'BUNDLE', b'Bundle')], verbose_name=b'Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(verbose_name=b'Subscription Expiry')),
                ('balance', models.IntegerField(verbose_name=b'Balance')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Product')),
            ],
        ),
    ]
